### ISSUE TITLE
files missing?  [sh: ./VirtualContext: No such file or directory]

### ISSUE THREAD

**Issue by jk3064** [GPUOpen-Tools/amd-codexl-analyzer#2]
Running on Linux (gentoo), I was able to compile it.
But when I try to run with `./CodeXLAnalyzer -c Tahiti -s opengl -a /tmp/output.txt  --vert myshader.glsl`
it returns

```
sh: ./VirtualContext: No such file or directory
Failed to read output: Resource temporarily unavailable
Building for Tahiti... failed.
```

So I searched the repo for VirtualContext:  `grep -iR VirtualContext /PATH_TO_DIR/amd-codexl-analyzer/*`
which tells me:
`amd-codexl-analyzer/CodeXL/Util/linux/JenkinsCodeXLFullBuild:           cp -f ${AMD_CODEXL}/../Common/Lib/AMD/OpenGL/VirtualContext/Release/lnx64/VirtualContext  ${PKG_NAME}`

important is here: **../Common/Lib/AMD/OpenGL/**
cause that dir is missing in the repo

Did I missed something or is the repo incomplete?

**Comment by AmitBM** [comment]
Hi jk3064,
OpenGL and Vulkan modes are powered by an additional executable, which serves as the backend.
This executable is expected to be published on March, with the release of CodeXL 2.0 (and will then be uploaded to the Analyzer github repository as well).
For now, please ignore the -vulkan and -opengl modes.
