### ISSUE TITLE
No Vulkan Support ?

### ISSUE THREAD

**Issue by dregen** [GPUOpen-Tools/amd-codexl-analyzer#5]
I didn't read anywhere if CodeXL supported Vulkan

**Comment by AmitBM** [comment]
CodeXL Analyzer supports offline compilation of Vulkan programs written in glsl. This is an experimental feature, that is based on Khronos' glslang as a front-end compiler. The Analyzer is currently planned to provide full live-driver support for Vulkan in the end of 2016.
To get the relevant CodeXL version, please visit https://github.com/GPUOpen-Tools/CodeXL

Please note that this repo (https://github.com/GPUOpen-Tools/amd-codexl-analyzer) does not contain the updated Analyzer code, as the Analyzer code was relocated under the CodeXL github tree. For the updated Analyzer code, visit https://github.com/GPUOpen-Tools/CodeXL/tree/master/CodeXL/Components/ShaderAnalyzer
