### ISSUE TITLE
Missing files: il_ops_table.h, ILFormatDecode.hpp, ILParser.h

### ISSUE THREAD

**Issue by Sineaggi** [GPUOpen-Tools/amd-codexl-analyzer#6]
ILShaderUtils.cpp makes various references to opcode tables and definitions that aren't included in the project. Are these going to be included in the future?

**Comment by AmitBM** [comment]
Are you referring to D3D10ShaderUtils.cpp? 
Can you please specify the full path to the .cpp file in question, and the line number where the opcode table is located/addressed in the .cpp file?

**Comment by Sineaggi** [comment]
I'm referring to Common/Src/ShaderUtils/IL/ILShaderUtils.cpp.
`#include "il_ops_table.h"` on line 30: [ILShaderUtils.cpp#L30](https://github.com/GPUOpen-Tools/amd-codexl-analyzer/blob/master/Common/Src/ShaderUtils/IL/ILShaderUtils.cpp#L30)
`#include "ILFormatDecode.hpp"` on line 28: [ILShaderUtils.cpp#L28](https://github.com/GPUOpen-Tools/amd-codexl-analyzer/blob/master/Common/Src/ShaderUtils/IL/ILShaderUtils.cpp#L28)
`#include "ILParser.h"` on line 20: [ILShaderUtils.cpp#L20](https://github.com/GPUOpen-Tools/amd-codexl-analyzer/blob/master/Common/Src/ShaderUtils/IL/ILShaderUtils.cpp#L20)

**Comment by AmitBM** [comment]
The files under Common/Src/ShaderUtils/IL/... are no longer referenced by the project. They should be removed soon. 

Please note that the Analyzer code was moved to the CodeXL github repo (now under https://github.com/GPUOpen-Tools/CodeXL/tree/master/CodeXL/Components/ShaderAnalyzer).

**Comment by Sineaggi** [comment]
I see. I was mostly curious because I've been looking for a definitive reference of the AMD IL opcode list, as well as parser/generator. Or is that all handled by the driver?

**Comment by AmitBM** [comment]
Check out this document: http://developer.amd.com/wordpress/media/2012/10/AMD_Intermediate_Language_(IL)_Specification_v2.pdf

The Analyzer doesn't parse IL code (except for a very limited parsing for syntax highlighting purposes).

**Comment by Sineaggi** [comment]
Thanks, yes I've been looking through that document but unfortunately the token opcodes that I've been reading out of the binary haven't lined up with anything that makes sense.

For example, in two binaries I've been working, IL_Lang and IL_Version, I get a token with opcode 0x15D . According to the enum list at the bottom of the document, the opcode with value 349 is `IL_OP_RCP_VEC`, which doesn't make any sense for a starter opcode. This makes me think that the enum list at the bottom of the document is either missing entries or otherwise incorrect.

Unfortunately the enums aren't valued, so I don't have any way to verify my disassembly. I also don't have access to my AMD graphics card at the moment, so it's doubly hard to verify.

Would you happen to know of an authoritative mapping of token values to tokens?

**Comment by Sineaggi** [comment]
To give you an example of what I'm trying to accomplish, the original shader looks like this:
```
struct VOut {
    float4 position : SV_POSITION;
    float4 color : COLOR;
};

Buffer<float4> positions : register(t0);
Buffer<float4> colors : register(t1);

VOut VShader(uint id : SV_VertexID) {
    VOut output;

    output.position = positions.Load(id);
    output.color = colors.Load(id);

    return output;
}
```
I've done most of the disassembly by hand, but the tokens seem off. `[RCP_VEC, CUT, CUT, DLC_VPRIM, DCL_INPUT, DCL_INPUT, RESINFO, RESINFO, RET_LOGICALZ, END]`
What makes more sense would be something like `[unknown, DCL_RES, DCL_RES, DCL_INPUT, DLC_OUTPUT, DCL_OUTPUT, LOAD, LOAD, RET_DYN, END]` where each of the tokens are at least 1 value off from what they should be according to the enum list. Again, since the ILOpCode enum list doesn't contain actual values, it's difficult to tell what dissassembly should be.
Here's the hex binary. `[0x15D, 0x80, 0x80, 0x7E, 0x7D, 0x7D, 0x86, 0x86, 0x73, 0x28]` would be my best guess at the opcode segmentation.
![hexxx](https://cloud.githubusercontent.com/assets/889237/15334139/1f28d8ac-1c2a-11e6-94c6-34d8f4e83a7e.PNG)
